# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Versions
versionConnector=3.0.0-beta.5
versionAdapterCore=2.0.53+26.1.2
versionAdapterRuntime=1.0.0+26.1.2

versionMc=26.1.2
versionNeoForge=26.1.2.95
versionLaunchpad=1.9.0+26.1.2
versionAutoRenamingTool=2.0.23
versionClassTweaker=0.3.0-beta.2
versionForgifiedFabricLoader=2.5.85+0.19.3+26.1.2
versionForgifiedFabricApi=0.155.2+26.1.2+3.5.0

# Publishing
curseForgeId=890127
modrinthId=u58R1TMW
githubRepository=Sinytra/Connector
# This is the branch the release tag will be created from
publishBranch=26.1.x
# Dependencies
forgifiedFabricApiCurseForge=forgified-fabric-api
forgifiedFabricApiModrinth=Aqlf1Shp
launchpadCurseForge=launchpad
launchpadModrinth=voWgQoWV
connectorExtrasCurseForge=connector-extras
connectorExtrasModrinth=FYpiwiBR
