# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Versions
versionConnector=3.0.0-beta.1
versionAdapterCore=2.0.36+1.21.1
versionAdapterRuntime=1.0.0+1.21.1

versionMc=26.1.2
versionNeoForge=26.1.2.76
versionLaunchpad=1.2.0+26.1.2+dev-g7d037fb
versionAutoRenamingTool=2.0.23
versionClassTweaker=0.3.0-beta.2
versionForgifiedFabricLoader=2.5.78+0.18.4+26.1
versionForgifiedFabricApi=0.152.1+3.0.6+26.1.2+local

# Publishing
curseForgeId=890127
modrinthId=u58R1TMW
githubRepository=Sinytra/Connector
# This is the branch the release tag will be created from
publishBranch=26.1.x
# Dependencies
forgifiedFabricApiCurseForge=forgified-fabric-api
forgifiedFabricApiModrinth=Aqlf1Shp
connectorExtrasCurseForge=connector-extras
connectorExtrasModrinth=FYpiwiBR

mixinextrasVersion=0.3.2
