name: Mod Incompatibility
description: Report an incompatible mod
labels: [compat]
body:
  - type: markdown
    attributes:
      value: "## Welcome!"
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to report this incompatibility!
        Make sure you are running the latest version of Connector and its dependencies before reporting.
  - type: input
    id: mod
    attributes: 
      label: Mod Name
      description: "Name of the problematic mod"
      placeholder: "Examplemod"
    validations:
      required: true
  - type: input
    id: homepage
    attributes: 
      label: Mod Homepage
      description: "A link to the mod's homepage. This can be its CurseForge, Modrinth, Github repository or something else."
      placeholder: "https://example.com"
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        How do you trigger this bug? Please walk us through it step by step.
        If applicable, add screenshots to help explain your problem. In case the mod crashes the game without
        ever loading, feel free to skip this step.
      value: |
        1.
        2.
        3.
        ...
  - type: input
    id: logs
    attributes:
      label: Logs
      description: |
        If applicable (crash, error output in console), please provide your crash report.
        Otherwise, we recommend uploading the debug.log found in your `.minecraft/logs` directory.
        To upload logs, use an external site to post the crash report, such as [Ubuntu Pastebin](https://paste.ubuntu.com/), [Pastebin](http://pastebin.com/), or [Github Gist](https://gist.github.com/)
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: "Add any other context about the problem here, such as the modpack you're playing or other mods that might be causing this bug."