package dev.su5ed.connector.fart;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import net.minecraftforge.fart.api.Transformer;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.Collection;
import java.util.List;

public class PackMetadataGenerator implements Transformer {
    public static final int DATA_PACK_FORMAT = 12;
    public static final int RESOURCE_PACK_FORMAT = 13;

    private final String modid;

    public PackMetadataGenerator(String modid) {
        this.modid = modid;
    }

    @Override
    public Collection<? extends Entry> getExtras() {
        JsonObject packMeta = new JsonObject();
        JsonObject pack = new JsonObject();
        JsonObject description = new JsonObject();
        description.addProperty("text", this.modid + " resources, generated by Connector");
        pack.add("description", description);
        pack.addProperty("forge:server_data_pack_format", DATA_PACK_FORMAT);
        pack.addProperty("pack_format", RESOURCE_PACK_FORMAT);
        packMeta.add("pack", pack);

        try (ByteArrayOutputStream byteStream = new ByteArrayOutputStream()) {
            try (Writer writer = new OutputStreamWriter(byteStream)) {
                new Gson().toJson(packMeta, writer);
                writer.flush();
            }
            byte[] data = byteStream.toByteArray();
            return List.of(ResourceEntry.create("pack.mcmeta", 318211200000L, data));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
